/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type PreviousPasswordEntity struct {
	Invalidated DateTime `json:"invalidated,omitempty"`
	Password    string   `json:"password,omitempty"`
}
