/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

// Sophos Central Endpoints Model
type EndpointsResponse struct {
	Filtered int32            `json:"filtered,omitempty"`
	Items    []EndpointEntity `json:"items,omitempty"`
	NextKey  string           `json:"next_key,omitempty"`
	Total    int32            `json:"total,omitempty"`
}
