/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type EndpointAdSyncInfo struct {
	Dn         string `json:"dn,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
	FromAdSync bool   `json:"from_ad_sync,omitempty"`
	Name       string `json:"name,omitempty"`
}
