/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

// Sophos Central Alert Model
type AlertAggregate struct {
	HasMore bool          `json:"has_more,omitempty"`
	Items   []AlertEntity `json:"items,omitempty"`
	// Value of the next cursor. This will be used to make next call of api
	NextCursor string `json:"next_cursor,omitempty"`
}
