/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type CoreRemedyItem struct {
	Descriptor string `json:"descriptor,omitempty"`
	Result     string `json:"result,omitempty"`
	Type       string `json:"type,omitempty"`
}
