/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type EndpointWhitelistProperties struct {
	Property string `json:"property,omitempty"`
	Type     string `json:"type,omitempty"`
}
