/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type CoreRemedyItems struct {
	Items      []CoreRemedyItem `json:"items,omitempty"`
	TotalItems int32            `json:"totalItems,omitempty"`
}
