/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

import (
	"time"
)

type ObjectId struct {
	Counter           int32     `json:"counter,omitempty"`
	Date              time.Time `json:"date,omitempty"`
	MachineIdentifier int32     `json:"machineIdentifier,omitempty"`
	ProcessIdentifier int32     `json:"processIdentifier,omitempty"`
	Time              int64     `json:"time,omitempty"`
	TimeSecond        int32     `json:"timeSecond,omitempty"`
	Timestamp         int32     `json:"timestamp,omitempty"`
}
