/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

// Sophos Central Hashes Model
type HashesResponse struct {
	Hashes map[string]interface{} `json:"hashes,omitempty"`
}
