/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

// This model wraps up an Event. This contains various fields that contain information regarding the event that was generated.
type LegacyEventEntity struct {
	// Certificate info of the application associated with the threat, if available
	AppCerts []EndpointCoreEventCertificate `json:"appCerts,omitempty"`
	// SHA 256 hash of the application associated with the threat, if available
	AppSha256       string          `json:"appSha256,omitempty"`
	CoreRemedyItems CoreRemedyItems `json:"core_remedy_items,omitempty"`
	// The date at which the event was created
	CreatedAt string `json:"created_at,omitempty"`
	// The identifier of the customer for which record is created
	CustomerId string                `json:"customer_id,omitempty"`
	Details    []EventDetailProperty `json:"details,omitempty"`
	// The corresponding endpoint id associated with the record
	EndpointId string `json:"endpoint_id,omitempty"`
	// The corresponding endpoint type associated with the record
	EndpointType string `json:"endpoint_type,omitempty"`
	// The group associated with the group
	Group string `json:"group,omitempty"`
	// The Identifier for the event
	Id string `json:"id,omitempty"`
	// The location captured for this record
	Location string `json:"location,omitempty"`
	// The name of the record created
	Name string `json:"name,omitempty"`
	// originating component of a detection
	Origin string `json:"origin,omitempty"`
	// The severity for this alert
	Severity string `json:"severity,omitempty"`
	// The source for this record
	Source string `json:"source,omitempty"`
	// Detailed source information for this record
	SourceInfo map[string]string `json:"source_info,omitempty"`
	// The threat associated with the record
	Threat string `json:"threat,omitempty"`
	// The type of this record
	Type string `json:"type,omitempty"`
	// The identifier of the user for which record is created
	UserId string `json:"user_id,omitempty"`
	// The date at which the event was created
	When                string                        `json:"when,omitempty"`
	WhitelistProperties []EndpointWhitelistProperties `json:"whitelist_properties,omitempty"`
}
