/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type DateTimeZone struct {
	Fixed bool   `json:"fixed,omitempty"`
	Id    string `json:"id,omitempty"`
}
