/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type TamperProtectionEntity struct {
	Enabled           bool                     `json:"enabled,omitempty"`
	GloballyEnabled   bool                     `json:"globally_enabled,omitempty"`
	Password          string                   `json:"password,omitempty"`
	PreviousPasswords []PreviousPasswordEntity `json:"previous_passwords,omitempty"`
}
