/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type CustomerFeature struct {
	ExpirationProcessed    bool     `json:"expirationProcessed,omitempty"`
	Expired                bool     `json:"expired,omitempty"`
	ExpiresOn              DateTime `json:"expiresOn,omitempty"`
	FeatureCode            string   `json:"featureCode,omitempty"`
	GeneratedFromLicenseId string   `json:"generatedFromLicenseId,omitempty"`
	LicenseCode            string   `json:"licenseCode,omitempty"`
	Protection             bool     `json:"protection,omitempty"`
	Valid                  bool     `json:"valid,omitempty"`
}
