/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

// Sophos Central Event Model
type EventAggregate struct {
	HasMore bool                `json:"has_more,omitempty"`
	Items   []LegacyEventEntity `json:"items,omitempty"`
	// Value of the next cursor. This will be used to make next call of api
	NextCursor string `json:"next_cursor,omitempty"`
}
