/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

// This model wraps up an Alert. This contains various fields that contain information regarding the alert that was generated.
type AlertEntity struct {
	// The date at which the alert was created
	CreatedAt string `json:"created_at,omitempty"`
	// The unique identifier of the customer linked with this record
	CustomerId string      `json:"customer_id,omitempty"`
	Data       interface{} `json:"data,omitempty"`
	// The description of the alert that was generated
	Description string `json:"description,omitempty"`
	// The Event Services event id
	EventServiceEventId string `json:"event_service_event_id,omitempty"`
	// Identifier for the alert
	Id   string                            `json:"id,omitempty"`
	Info map[string]map[string]interface{} `json:"info,omitempty"`
	// The location captured for this record
	Location string `json:"location,omitempty"`
	// The severity for this alert
	Severity string `json:"severity,omitempty"`
	// Describes the source from alert was generated
	Source string `json:"source,omitempty"`
	// The name of the threat responsible for the generation of alert
	Threat          string `json:"threat,omitempty"`
	ThreatCleanable bool   `json:"threat_cleanable,omitempty"`
	// Describes the type of the device on which alert was generated
	Type string `json:"type,omitempty"`
	// The date at which the alert was created
	When string `json:"when,omitempty"`
}
