/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type DateTime struct {
	AfterNow       bool         `json:"afterNow,omitempty"`
	BeforeNow      bool         `json:"beforeNow,omitempty"`
	CenturyOfEra   int32        `json:"centuryOfEra,omitempty"`
	Chronology     Chronology   `json:"chronology,omitempty"`
	DayOfMonth     int32        `json:"dayOfMonth,omitempty"`
	DayOfWeek      int32        `json:"dayOfWeek,omitempty"`
	DayOfYear      int32        `json:"dayOfYear,omitempty"`
	EqualNow       bool         `json:"equalNow,omitempty"`
	Era            int32        `json:"era,omitempty"`
	HourOfDay      int32        `json:"hourOfDay,omitempty"`
	Millis         int64        `json:"millis,omitempty"`
	MillisOfDay    int32        `json:"millisOfDay,omitempty"`
	MillisOfSecond int32        `json:"millisOfSecond,omitempty"`
	MinuteOfDay    int32        `json:"minuteOfDay,omitempty"`
	MinuteOfHour   int32        `json:"minuteOfHour,omitempty"`
	MonthOfYear    int32        `json:"monthOfYear,omitempty"`
	SecondOfDay    int32        `json:"secondOfDay,omitempty"`
	SecondOfMinute int32        `json:"secondOfMinute,omitempty"`
	WeekOfWeekyear int32        `json:"weekOfWeekyear,omitempty"`
	Weekyear       int32        `json:"weekyear,omitempty"`
	Year           int32        `json:"year,omitempty"`
	YearOfCentury  int32        `json:"yearOfCentury,omitempty"`
	YearOfEra      int32        `json:"yearOfEra,omitempty"`
	Zone           DateTimeZone `json:"zone,omitempty"`
}
