/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type EndpointCoreEventCertificate struct {
	Signer     string `json:"signer,omitempty"`
	Thumbprint string `json:"thumbprint,omitempty"`
}
