/*
 * Sophos Public API
 *
 * Swagger Specifications for public APIs
 *
 * API version: beta
 * Contact: support@sophos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sophoscentral

type CustomerLicense struct {
	Expired     bool     `json:"expired,omitempty"`
	ExpiresOn   DateTime `json:"expires_on,omitempty"`
	Id          ObjectId `json:"id,omitempty"`
	LicenseCode string   `json:"license_code,omitempty"`
	LicenseId   string   `json:"license_id,omitempty"`
	LicenseType string   `json:"license_type,omitempty"`
	Quota       int32    `json:"quota,omitempty"`
	StartsOn    DateTime `json:"starts_on,omitempty"`
	Suspended   bool     `json:"suspended,omitempty"`
}
